version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout

       Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "backend/requirements.txt" }}
           fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r backend/requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "backend/requirements.txt" }}

      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'

      - restore_cache:
          key: dependency-cache-{{ checksum "frontend/package.json" }}

      - run:
          name: Install npm wee
          command: npm install

      - save_cache:
          key: dependency-cache-{{ checksum "frontend/package.json" }}
          paths:
            - node_modules

      - run:
          name: Angular CLI
          command: npm install @angular/cli@latest -g
        
      - run:
        name: Build
        command: ng build

      - store_artifacts:
          path: test-reports
          destination: test-reports

