version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout

      - run: 
          name: Install npm
          command: |
            curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
            sudo apt-get install -y nodejs

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "backend/requirements.txt" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r backend/requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "backend/requirements.txt" }}

      - restore_cache:
          key: dependency-cache-{{ checksum "frontend/package.json" }}

      - save_cache:
          key: dependency-cache-{{ checksum "frontend/package.json" }}
          paths:
            - node_modules

      - run:
          name: Angular CLI
          command: sudo npm install @angular/cli@latest -g
        
      - run:
          name: Build
          command: |
            cd frontend
            sudo ng build

      - store_artifacts:
          path: test-reports
          destination: test-reports

